### ISSUE TITLE
Fix HTTPS/SSL

### ISSUE THREAD

**Issue by puyoxyz** [cpback/game#1]
cpback.club, www.cpback.club and play.cpback.club already have SSL support, but the game does not work on play.cpback.club because media.cpback.club does not have SSL. Here's the error directly from the browser's console from when you try to load play.cpback.club with SSL:

`Mixed Content: The page at 'https://play.cpback.club/' was loaded over HTTPS, but requested an insecure plugin data 'http://media.cpback.club/play/v2/client/load.swf'. This content should also be served over HTTPS.`

**Comment by puyoxyz** [comment]
Update, media.cpback.club has SSL but play.cpback.club on SSL still loads non-SSL version of media page. This could be fixed by redirecting all insecure HTTP traffic to HTTPS/SSL secure traffic

@tbhjayson assigning you, please do this:
log into https://dash.cloudflare.com, pick cpback.club, go to the SSL/TLS tab, go to Edge Certificates sub-tab and enable "Always Use HTTPS"

close this issue when youre done

**Comment by tbhjayson** [comment]
fixed
