### ISSUE TITLE
Brown Puffle disappears after trying to walk it

### ISSUE THREAD

**Issue by tbhjayson** [cpback/game#11]
![image](https://user-images.githubusercontent.com/59205107/72752203-d7c2b000-3b7e-11ea-8ab3-c75af8fa775b.png)
![image](https://user-images.githubusercontent.com/59205107/72752213-ddb89100-3b7e-11ea-9a0a-ba1cee52e780.png)

**Comment by puyoxyz** [comment]
Might be happening with more puffles?

![](https://image-host.club/U7hpUl7X.png)

**Comment by puyoxyz** [comment]
woops sorry meant to assign calvin

**Comment by puyoxyz** [comment]
calvin fixed this im p sure
