### ISSUE TITLE
Brown Puffle House price

### ISSUE THREAD

**Issue by tbhjayson** [cpback/game#12]
It says it's free but it actually costs 500 coins.
![image](https://user-images.githubusercontent.com/59205107/72752271-fde85000-3b7e-11ea-8a91-a4e77bc5c962.png)
![image](https://user-images.githubusercontent.com/59205107/72752276-ffb21380-3b7e-11ea-9469-06e9a7ab3ecc.png)

**Comment by puyoxyz** [comment]
Please report pricing issues at #9 in comments. @tbhjayson
